[package]
name = "rust-crossword"
version = "0.1.0"
authors = ["lynxs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
log = "0.4.8"
thiserror = "1.0.19"